name: Daily Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: "30 3 * * *"   # India 9:00 AM (UTC+5:30)
  workflow_dispatch:

jobs:
  auto_commit_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update daily file
      run: |
        echo "Last update: $(date '+%Y-%m-%d %H:%M:%S')" > daily_update.txt

    - name: Commit changes
      run: |
        git config --global user.name "Krishna Das Meena"
        git config --global user.email "mek127142@gmail.com"
        git add .
        git commit -m "Daily auto commit: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"

    - name: Push changes
      run: git push
